language: node_js
node_js:
  - 8.11
sudo: false
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  directories:
    - node_modules
notifications:
  email:
    - markus.felten@gmx.de
before_script:
  - npm prune
after_success:
  - npm run semantic-release
